INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UM_USER',1);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UM_ROLE',1);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UM_USERGROUP',1);
COMMIT;
INSERT INTO UM_USER(ID,LOGIN_NAME,USER_NAME,PASSWORD,STATE,CREATE_TIME) VALUES(1,'admin','管理员','C4CA4238A0B923820DCC509A6F75849B',0,SYSTIMESTAMP);
COMMIT;
INSERT INTO UM_ROLE(ID,NAME,CREATE_TIME,DESCRIPTION,TYPE) VALUES(1,'系统管理员',SYSTIMESTAMP,'',0);
COMMIT;
INSERT INTO UM_USERGROUP(DESCRIPTION,ID,NAME,PARENT_ID,TYPE) VALUES('',0,'所有组',0,0);
INSERT INTO UM_USERTOROLE(ROLE_ID,USER_ID) VALUES (1,1);
--删除原有授权
DELETE FROM UM_ROLEAUTHORITY;
DELETE FROM UM_FUNCTION;
--权限
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (0, 0, '系统权限', null, null, 0, null, 0, 0);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000000, 0, '账户管理', null, "fa-users", 0, null, 0, 8);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (90000000, 0, '系统设置', null, "fa-cogs", 0, null, 0, 9);
--用户管理
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000100, 80000000, '用户管理', 'userManage', null, 0, null, 0, 1);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000200, 80000000, '人员管理', 'personManage', null, 0, null, 0, 2);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000300, 80000000, '分组管理', 'groupManage', null, 0, null, 0, 3);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000400, 80000000, '角色管理', 'roleManage', null, 0, null, 0, 4);
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (80000500, 80000000, '权限管理', 'permissionManage', null, 0, null, 0, 5);
COMMIT;
--系统管理
insert into UM_FUNCTION (ID, PARENT_ID, NAME, PARAM, ICON, STATE, DESCRIPTION, TYPE, VIEW_POS) values (90000100, 90000000, '受控词管理', 'controlWordManage', null, 0, null, 0, 1);
COMMIT;
--添加权限
INSERT INTO UM_ROLEAUTHORITY (ROLE_ID,FUNCTION_ID) SELECT 1,ID FROM UM_FUNCTION WHERE (TYPE=1 OR PARENT_ID>100) AND ID NOT IN (SELECT FUNCTION_ID FROM UM_ROLEAUTHORITY);
COMMIT;